jobs:
  include:
  - name: Mock Run
    script:
    - npm install
    - mkdir someDir
    - cp package-lock.json someDir/
deploy:
  provider: s3
  access_key_id: $S3_KEY_ID
  secret_access_key: $S3_ACCESS_KEY
  bucket: centchain
  endpoint: https://nyc3.digitaloceanspaces.com
  local_dir: someDir
  glob: package-lock.json
  upload-dir: $TRAVIS_COMMIT-$TRAVIS_BUILD
  acl: private
  skip_cleanup: true
  on:
    repo: ansermino/travis-test
